### ISSUE TITLE
Unable to add package [com.nomnom.unity-lc-project-patcher@https://github.com/nomnomab/unity-lc-project-patcher.git]

### ISSUE THREAD

**Issue by pedro9006** [nomnomab/unity-lc-project-patcher#1]
I needed update my custom moon to the latest version of Lethal Company, an ended up needing to update the Unity Project Patcher, the Lethal Company Project Patcher, and the Unity Project Patcher BepInEx. However, attempting to update or reinstall any of these just leads to this error.
![image_2024-08-07_145841419](https://github.com/user-attachments/assets/fb22c923-2ace-463c-9e4b-f76319be7ddc)
![image_2024-08-07_145858455](https://github.com/user-attachments/assets/b5315e0b-5bc4-43d5-a26b-518816da77e8)
![image_2024-08-07_145928386](https://github.com/user-attachments/assets/d255d89a-e046-4792-9ce4-83d5e1de2c7e)

Any help fixing this would be much appreciated.

**Comment by nomnomab** [comment]
Huh, I've never seen that error before, how weird. Have you tried restarting your pc or closing the project + completely restarting the hub (from bottom-right taskbar)? It seems like a state issue between unity and git somehow.

**Comment by pedro9006** [comment]
Yes, i've tried restarting my computer, as well as the project and unity hub. I'm trying this on a backup of my actual project which i made by copy pasting it and then adding project from disk using the unity hub.
![image_2024-08-07_160731058](https://github.com/user-attachments/assets/93a3d70b-c477-4914-8efb-084024efb793)

**Comment by nomnomab** [comment]
Currently looking around for others who have run into this, and also trying to replicate it (to no avail). 

Does this also happen in a new empty project? I tested on my end and it pulls it fine, so if it works in an empty project on your end, then it's something acting weird in the project somehow. If not, then also try a normal `git clone` to see if a normal clone works at all.

**Comment by nomnomab** [comment]
Another thing to try is to remove the entries for those packages in `Packages/packages-lock.json` (or even delete the entire file) and then re-focus unity to force a re-pull of everything.

**Comment by nomnomab** [comment]
If that also does not work, a hail-mary approach can be to close the project, delete `Library/` and `Packages/packages-lock.json`, and then re-open the project so it rebuilds the internals. That seems to be the suggested fix from the unity docs for package manager issues.

**Comment by pedro9006** [comment]
Okay, i'm sure this is an error on my end. In my actual project (Not the backup) i was able update each package no problem. I don't necessarily know the difference between the two besides the different directories they're in, but most likely i'll end up just copying the packages i updated from the actual project to the backup.

**Comment by nomnomab** [comment]
Super strange. I guess try the library and packages-lock removal above and see if it fixes the backup (or whichever project isn't the original to make sure it works):

> If that also does not work, a hail-mary approach can be to close the project, delete `Library/` and `Packages/packages-lock.json`, and then re-open the project so it rebuilds the internals. That seems to be the suggested fix from the unity docs for package manager issues.

**Comment by pedro9006** [comment]
> Super strange. I guess try the library and packages-lock removal above and see if it fixes the backup (or whichever project isn't the original to make sure it works):
> 
> > If that also does not work, a hail-mary approach can be to close the project, delete `Library/` and `Packages/packages-lock.json`, and then re-open the project so it rebuilds the internals. That seems to be the suggested fix from the unity docs for package manager issues.

Good news! I did find the issue. if anyone else has this issue, they should be sure to check the harddrive's file system. apparently hard-drives with an exFAT file system breaks the files. still don't understand how, but it does.

![image_2024-08-08_113704344](https://github.com/user-attachments/assets/cb6567e5-8eec-42e8-836d-dba3f98fc714)
![image_2024-08-08_113744746](https://github.com/user-attachments/assets/e7da2655-ff72-4bc9-9677-a820771009ee)
![image_2024-08-08_113917105](https://github.com/user-attachments/assets/d0537867-e4f7-4a60-90d6-0d184d0d166a)

**Comment by nomnomab** [comment]
Wow that is super obscure haha, when I have time I'll put that in the FAQ in case others run into it.

Thanks!
